# Generated by Django 4.2.6 on 2023-10-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('V2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distanceprice',
            name='day',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='distanceprice',
            name='updated_time',
            field=models.DateTimeField(),
        ),
    ]
