# Generated by Django 4.2.6 on 2023-10-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('V2', '0002_alter_distanceprice_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitingcharge',
            old_name='time_taken',
            new_name='per_min',
        ),
        migrations.AlterField(
            model_name='distanceprice',
            name='day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='timemultiplierfactor',
            name='updated_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='waitingcharge',
            name='updated_time',
            field=models.DateTimeField(),
        ),
    ]
