# Generated by Django 4.2.6 on 2023-10-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('V2', '0003_rename_time_taken_waitingcharge_per_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distancepricetype',
            name='created_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='distancepricetype',
            name='updated_time',
            field=models.DateTimeField(null=True),
        ),
    ]
