# Generated by Django 4.2.6 on 2023-10-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('V2', '0006_distanceadditionalprice_distancebaseprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distanceadditionalprice',
            name='day',
        ),
    ]
